/* -------------------------------------------------------
   THE DEEP SCAN AUDIT SCRIPT (PROJECT: LONDON LAVA)
   AUTHOR: DJANGO & THE ARCHITECT
   MISSION: CAPTURE EVERY LETTER. ESM COMPLIANT.
   -------------------------------------------------------
*/

import fs from 'fs';
import path from 'path';

// CONFIG: OUTPUT FILE
const OUTPUT_FILE = 'full_web_audit.txt';

// CONFIG: IGNORE LIST (NOISE)
const IGNORE_DIRS = [
  'node_modules', 
  '.git', 
  'dist', 
  'build', 
  '.firebase',
  'coverage'
];

// CONFIG: FILE EXTENSIONS TO CAPTURE
const ALLOWED_EXTS = [
  '.js', '.jsx', '.ts', '.tsx', 
  '.css', '.scss', 
  '.html', '.json'
];

// CONFIG: SPECIFIC FILES TO IGNORE
const IGNORE_FILES = [
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'full_nearaura_audit.txt',
  OUTPUT_FILE,
  'audit_web.js',
  'shoot.js'
];

let fileCount = 0;

function scanDirectory(dir, stream) {
  const files = fs.readdirSync(dir);

  for (const file of files) {
    const fullPath = path.join(dir, file);
    
    try {
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
          if (!IGNORE_DIRS.includes(file)) {
            scanDirectory(fullPath, stream);
          }
        } else {
          const ext = path.extname(file).toLowerCase();
          
          // CHECK FILTER
          if (ALLOWED_EXTS.includes(ext) && !IGNORE_FILES.includes(file)) {
            console.log(`[SCAN] 👁️ Reading: ${fullPath}`);
            
            const content = fs.readFileSync(fullPath, 'utf8');
            
            // WRITE HEADER
            stream.write(`\n\n================================================================================\n`);
            stream.write(`FILE: ${fullPath}\n`);
            stream.write(`================================================================================\n`);
            
            // WRITE CONTENT
            stream.write(content);
            
            fileCount++;
          }
        }
    } catch (err) {
        console.error(`[SKIP] Could not read ${fullPath}: ${err.message}`);
    }
  }
}

// EXECUTE
console.log("HOOOOOOOOOOOOFFFFFFFFFFFFFFFFFFFFFFFFf! 🛡️ STARTING DEEP SCAN (ESM MODE)...");
const stream = fs.createWriteStream(OUTPUT_FILE, { flags: 'w' });

// HEADER FOR THE AUDIT
stream.write(`NEARAURA WEB AUDIT - GENERATED BY THE ARCHITECT\n`);
stream.write(`DATE: ${new Date().toISOString()}\n`);
stream.write(`--------------------------------------------------\n`);

// START SCAN FROM CURRENT DIR
scanDirectory('.', stream);

stream.end(() => {
  console.log("-------------------------------------------------------");
  console.log(`✅ SCAN COMPLETE. Scanned ${fileCount} files.`);
  console.log(`✅ OUTPUT SAVED TO: ${OUTPUT_FILE}`);
  console.log(`👉 UPLOAD THIS FILE SO I CAN SEE THE MATRIX.`);
  console.log("-------------------------------------------------------");
  console.log("AUIGHT. 🛡️🦁");
});