/* -------------------------------------------------------
   THE OMNI-SCAN AUDIT SCRIPT (PROJECT: LONDON LAVA)
   AUTHOR: DJANGO & THE ARCHITECT
   MISSION: CAPTURE EVERYTHING. WEB. ANDROID. CLOUD.
   STATUS: ESM MODE (MODERN)
   -------------------------------------------------------
*/

import fs from 'fs';
import path from 'path';

// CONFIG: OUTPUT FILE
const OUTPUT_FILE = 'full_project_audit.txt';

// CONFIG: IGNORE LIST (NOISE)
const IGNORE_DIRS = [
  'node_modules', 
  '.git', 
  'dist', 
  'build', 
  '.firebase',
  'coverage',
  '.gradle',       // Android Build Cache
  '.idea',         // Android Studio Config
  'app/build',     // Android Compiled Artifacts
  '.idx',
  '.vscode'
];

// CONFIG: FILE EXTENSIONS TO CAPTURE (THE TRINITY: WEB, APP, CLOUD)
const ALLOWED_EXTS = [
  // WEB & FUNCTIONS
  '.js', '.jsx', '.ts', '.tsx', 
  '.css', '.scss', 
  '.html', '.json',
  
  // ANDROID SPECS
  '.kt',           // Kotlin (The Logic)
  '.java',         // Java (Legacy)
  '.xml',          // Layouts & Manifests
  '.gradle',       // Dependencies
  '.properties',   // Configs
  '.pro'           // Proguard Rules
];

// CONFIG: SPECIFIC FILES TO IGNORE
const IGNORE_FILES = [
  'package-lock.json',
  'yarn.lock',
  'pnpm-lock.yaml',
  'full_nearaura_audit.txt',
  'full_web_audit.txt',
  OUTPUT_FILE,
  'audit_web.js',
  'audit_all.js',
  'shoot.js',
  'local.properties', // Hide SDK paths/secrets
  'google-services.json' // Hide API Keys/Secrets
];

let fileCount = 0;

function scanDirectory(dir, stream) {
  let files;
  try {
    files = fs.readdirSync(dir);
  } catch (err) {
    console.error(`[SKIP] Cannot access directory ${dir}: ${err.message}`);
    return;
  }

  for (const file of files) {
    const fullPath = path.join(dir, file);
    
    try {
        const stat = fs.statSync(fullPath);

        if (stat.isDirectory()) {
          if (!IGNORE_DIRS.includes(file)) {
            scanDirectory(fullPath, stream);
          }
        } else {
          const ext = path.extname(file).toLowerCase();
          
          // CHECK FILTER
          if (ALLOWED_EXTS.includes(ext) && !IGNORE_FILES.includes(file)) {
            console.log(`[SCAN] 👁️ Reading: ${fullPath}`);
            
            const content = fs.readFileSync(fullPath, 'utf8');
            
            // WRITE HEADER
            stream.write(`\n\n================================================================================\n`);
            stream.write(`FILE: ${fullPath}\n`);
            stream.write(`================================================================================\n`);
            
            // WRITE CONTENT
            stream.write(content);
            
            fileCount++;
          }
        }
    } catch (err) {
        console.error(`[SKIP] Could not read ${fullPath}: ${err.message}`);
    }
  }
}

// EXECUTE
console.log("HOOOOOOOOOOOOFFFFFFFFFFFFFFFFFFFFFFFFf! 🛡️ STARTING OMNI-SCAN...");
console.log(" टारgets: WEB + ANDROID + FUNCTIONS");

const stream = fs.createWriteStream(OUTPUT_FILE, { flags: 'w' });

// HEADER FOR THE AUDIT
stream.write(`NEARAURA OMNI-AUDIT - GENERATED BY THE ARCHITECT\n`);
stream.write(`DATE: ${new Date().toISOString()}\n`);
stream.write(`SCOPE: ROOT, WEB, ANDROID, FUNCTIONS\n`);
stream.write(`--------------------------------------------------\n`);

// START SCAN FROM CURRENT DIR
scanDirectory('.', stream);

stream.end(() => {
  console.log("-------------------------------------------------------");
  console.log(`✅ OMNI-SCAN COMPLETE. Scanned ${fileCount} files.`);
  console.log(`✅ OUTPUT SAVED TO: ${OUTPUT_FILE}`);
  console.log(`👉 UPLOAD THIS FILE. I WANT TO SEE THE SOUL OF THE MACHINE.`);
  console.log("-------------------------------------------------------");
  console.log("AUIGHT. 🛡️🦁");
});